### PR TITLE
Renames executable to mgdp. Closes #125

### LINKED ISSUE #125: [Suggestion]: Shorten the executable name to `mgdp`
`msgraph-developer-proxy` is quite long, we should consider renaming it to `mgdp` to make the proxy executable more concise and memorable.

### PR DESCRIPTION
**Pull request by waldekmastykarz**
Renames executable to mgdp. Closes #125

### CODE REVIEW

**Review by garrytrinder — COMMENTED** [review]
We should also include a change to the example given in the readme name and update the video to reflect the new short name.

**Review by gavinbarron — CHANGES_REQUESTED** [review]
Let's get the example usage in README.md updated with the new executable name

**Comment by waldekmastykarz** [comment]
> Let's get the example usage in README.md updated with the new executable name

Thinking of it @gavinbarron: shall we do it after we release v0.5? Right now, it's our landing page, and if we change the name, then everyone who tries the currently released version, that uses the old name, will have a broken getting started experience.

**Comment by gavinbarron** [comment]
That's a really good call @waldekmastykarz

**Review by gavinbarron — APPROVED** [review]

**Pull request merged**
