### PR TITLE
Adds odata paging guidance. Closes #151

### LINKED ISSUE #151: Guidance: Is my app correctly supporting paging guidance
Offer guidance that verifies that apps properly handle retrieving multiple pages of data by using OData next page links rather than building links themselves. Include handling `$skip` values and cursors.

### PR DESCRIPTION
**Pull request by waldekmastykarz**
Adds odata paging guidance. Closes #151 

I also found a bug in how we resolve hosts to watch, where hosts with wildcards like `*.sharepoint.*` would be incorrectly processed for RegEx and invalid.

### CODE REVIEW

**Comment by sebastienlevert** [comment]
First thing that comes to mind... Should we have a series of aka.ms links that we control to be able to change location of guidance docs if they ever change without re-releasing a new version of the proxy? That should apply to all links we link to.

**Comment by waldekmastykarz** [comment]
Good idea! 👍

**Comment by waldekmastykarz** [comment]
> First thing that comes to mind... Should we have a series of aka.ms links that we control to be able to change location of guidance docs if they ever change without re-releasing a new version of the proxy? That should apply to all links we link to.

Thinking of it: shall we take it on a separate issue, so that we can consistently update all links in one go?

**Comment by sebastienlevert** [comment]
> Thinking of it: shall we take it on a separate issue, so that we can consistently update all links in one go?

I think so!

**Review by gavinbarron — APPROVED** [review]

**Pull request merged**
